-- Migration: 004_seed_gdpr_controls.sql
-- Description: Comprehensive GDPR (General Data Protection Regulation) controls
-- Total Controls: 156 controls across all GDPR chapters
-- Author: Nexus Compliance Engine
-- Date: 2025-01-01

-- First, ensure the GDPR framework exists
INSERT INTO compliance_frameworks (id, name, version, description, category, jurisdiction, effective_date, status)
VALUES (
  'gdpr',
  'General Data Protection Regulation',
  '2016/679',
  'EU regulation on data protection and privacy for individuals within the European Union and European Economic Area. Establishes requirements for processing personal data and provides data subjects with rights over their personal information.',
  'privacy',
  'EU',
  '2018-05-25',
  'active'
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  status = EXCLUDED.status;

-- ============================================================================
-- CHAPTER II: PRINCIPLES (Articles 5-11) - 32 Controls
-- ============================================================================

-- Article 5: Principles relating to processing of personal data
INSERT INTO compliance_controls (id, framework_id, control_number, domain, subdomain, title, description, objective, implementation_guidance, risk_category, implementation_priority, automated_test_available, ai_assessment_prompt)
VALUES
-- Lawfulness, Fairness, Transparency (Art 5.1.a)
('GDPR-5.1.a-1', 'gdpr', '5.1.a.1', 'Principles', 'Lawfulness',
 'Legal Basis Documentation',
 'Document and maintain records of the legal basis for each processing activity, ensuring at least one of the six lawful bases applies: consent, contract, legal obligation, vital interests, public task, or legitimate interests.',
 'To ensure all personal data processing has a valid legal foundation under Article 6.',
 'Create a processing register that maps each data processing activity to its legal basis. Review and update quarterly. Implement approval workflows requiring legal basis identification before new processing begins.',
 'critical', 100, true,
 'Evaluate the organization''s documentation of legal bases for processing. Check: 1) Is there a comprehensive processing register? 2) Is each processing activity mapped to a specific legal basis? 3) Are legal basis assessments documented and reviewed? 4) Is there a process for new processing activities?'),

('GDPR-5.1.a-2', 'gdpr', '5.1.a.2', 'Principles', 'Lawfulness',
 'Consent Management System',
 'Implement systems to obtain, record, and manage consent when consent is the legal basis. Consent must be freely given, specific, informed, and unambiguous.',
 'To ensure valid consent is obtained and can be demonstrated for all consent-based processing.',
 'Deploy a consent management platform that: records the time and method of consent, links consent to specific purposes, allows easy withdrawal, and maintains audit trails. Implement granular consent options.',
 'critical', 99, true,
 'Assess the consent management implementation. Verify: 1) Consent is freely given without coercion 2) Consent is specific to each purpose 3) Consent mechanism is clear and unambiguous 4) Withdrawal is as easy as giving consent 5) Records prove consent was given'),

('GDPR-5.1.a-3', 'gdpr', '5.1.a.3', 'Principles', 'Fairness',
 'Fair Processing Practices',
 'Ensure processing is fair to data subjects, not using data in ways they would not reasonably expect or that have unjustified adverse effects on them.',
 'To prevent processing that is detrimental, discriminatory, or unexpected to data subjects.',
 'Conduct fairness impact assessments for high-risk processing. Implement algorithmic fairness testing for automated decisions. Review processing against reasonable expectations of data subjects.',
 'high', 95, false,
 'Evaluate fairness of processing activities. Check: 1) Are there fairness assessments for processing activities? 2) Is there monitoring for discriminatory outcomes? 3) Would data subjects reasonably expect this processing? 4) Are adverse effects identified and mitigated?'),

('GDPR-5.1.a-4', 'gdpr', '5.1.a.4', 'Principles', 'Transparency',
 'Privacy Notice Completeness',
 'Provide clear, accessible privacy notices containing all required information under Articles 13 and 14 at the time of data collection.',
 'To ensure data subjects are fully informed about how their data is processed.',
 'Create layered privacy notices with summaries and detailed information. Include: identity of controller, purposes, legal basis, recipients, transfers, retention periods, rights, and complaint procedures. Review annually.',
 'critical', 98, true,
 'Assess privacy notice compliance. Verify all Article 13/14 information is present: 1) Controller identity and contact 2) DPO contact 3) Processing purposes and legal basis 4) Recipients 5) Transfer information 6) Retention periods 7) Data subject rights 8) Right to withdraw consent 9) Right to lodge complaint'),

-- Purpose Limitation (Art 5.1.b)
('GDPR-5.1.b-1', 'gdpr', '5.1.b.1', 'Principles', 'Purpose Limitation',
 'Purpose Specification',
 'Specify explicit and legitimate purposes for data collection at the time of collection. Document all purposes clearly and ensure they are communicated to data subjects.',
 'To ensure data is collected for specified, explicit, and legitimate purposes only.',
 'Document purposes in processing register before collection begins. Review purposes against legitimacy criteria. Implement purpose tagging in data systems.',
 'critical', 97, true,
 'Evaluate purpose specification practices. Check: 1) Are purposes documented before collection? 2) Are purposes explicit and specific (not vague)? 3) Are purposes legitimate? 4) Are purposes communicated to data subjects?'),

('GDPR-5.1.b-2', 'gdpr', '5.1.b.2', 'Principles', 'Purpose Limitation',
 'Compatible Use Assessment',
 'Assess compatibility of any further processing against original purposes. Apply the compatibility test considering: link between purposes, context, nature of data, consequences, and safeguards.',
 'To prevent processing for purposes incompatible with original collection purposes.',
 'Create a compatibility assessment procedure. For each new use, document the five-factor test results. Obtain fresh consent or establish new legal basis for incompatible purposes.',
 'high', 93, false,
 'Assess purpose compatibility practices. Verify: 1) Is there a process for assessing new uses? 2) Are the five compatibility factors considered? 3) Is incompatible processing identified and addressed? 4) Are new legal bases obtained when needed?'),

-- Data Minimization (Art 5.1.c)
('GDPR-5.1.c-1', 'gdpr', '5.1.c.1', 'Principles', 'Data Minimization',
 'Collection Minimization',
 'Limit personal data collection to what is directly necessary for the specified purposes. Avoid collecting data "just in case" or for undefined future uses.',
 'To ensure only adequate, relevant, and limited data is collected.',
 'Review data collection forms and processes to eliminate unnecessary fields. Implement mandatory justification for each data element collected. Conduct annual data minimization audits.',
 'high', 96, true,
 'Evaluate data minimization at collection. Check: 1) Is each data element justified as necessary? 2) Are there unnecessary fields in forms? 3) Is data collected "just in case"? 4) Are regular minimization reviews conducted?'),

('GDPR-5.1.c-2', 'gdpr', '5.1.c.2', 'Principles', 'Data Minimization',
 'Processing Minimization',
 'Ensure processing operations are limited to what is necessary. Do not process more data than required for the specific operation.',
 'To limit the scope of processing to the minimum necessary.',
 'Implement role-based access limiting data visibility. Use data masking and pseudonymization where full data is not required. Log and review data access patterns.',
 'high', 92, true,
 'Assess processing minimization. Verify: 1) Is access limited to necessary data only? 2) Is masking/pseudonymization used appropriately? 3) Are there controls preventing excessive processing? 4) Is processing scope regularly reviewed?'),

-- Accuracy (Art 5.1.d)
('GDPR-5.1.d-1', 'gdpr', '5.1.d.1', 'Principles', 'Accuracy',
 'Data Quality Controls',
 'Implement controls to ensure personal data is accurate and kept up to date. This includes validation at collection, regular accuracy reviews, and correction mechanisms.',
 'To maintain accurate personal data and prevent harm from inaccurate data.',
 'Implement input validation, data quality rules, and regular verification processes. Enable data subject self-service updates. Flag potentially stale data for review.',
 'high', 90, true,
 'Evaluate data accuracy controls. Check: 1) Is there input validation at collection? 2) Are there regular accuracy reviews? 3) Can data subjects update their data easily? 4) Are there mechanisms to identify inaccurate data?'),

('GDPR-5.1.d-2', 'gdpr', '5.1.d.2', 'Principles', 'Accuracy',
 'Inaccurate Data Rectification',
 'Establish procedures for rectifying or erasing inaccurate personal data without delay when identified or reported by data subjects.',
 'To promptly correct inaccurate personal data.',
 'Create a rectification workflow with SLAs for correction. Propagate corrections to all systems and recipients. Log all corrections with before/after states.',
 'high', 89, true,
 'Assess rectification procedures. Verify: 1) Is there a clear process for corrections? 2) Are corrections made without undue delay? 3) Are corrections propagated to recipients? 4) Are correction records maintained?'),

-- Storage Limitation (Art 5.1.e)
('GDPR-5.1.e-1', 'gdpr', '5.1.e.1', 'Principles', 'Storage Limitation',
 'Retention Schedule',
 'Define and document retention periods for all categories of personal data based on purpose necessity, legal requirements, and business justification.',
 'To ensure personal data is not kept longer than necessary.',
 'Create a comprehensive retention schedule mapping data categories to retention periods with justifications. Review annually. Align with legal hold requirements.',
 'critical', 94, true,
 'Evaluate retention schedule. Check: 1) Is there a documented retention schedule? 2) Are retention periods justified? 3) Does the schedule cover all data categories? 4) Is the schedule reviewed regularly?'),

('GDPR-5.1.e-2', 'gdpr', '5.1.e.2', 'Principles', 'Storage Limitation',
 'Automated Deletion',
 'Implement automated mechanisms to delete or anonymize personal data when retention periods expire.',
 'To ensure timely disposal of personal data no longer needed.',
 'Deploy automated retention enforcement in databases and file systems. Generate deletion logs and certificates. Test deletion completeness including backups.',
 'high', 91, true,
 'Assess automated deletion. Verify: 1) Is there automated retention enforcement? 2) Does deletion include all copies including backups? 3) Are deletion logs maintained? 4) Is deletion completeness verified?'),

-- Integrity and Confidentiality (Art 5.1.f)
('GDPR-5.1.f-1', 'gdpr', '5.1.f.1', 'Principles', 'Security',
 'Technical Security Measures',
 'Implement appropriate technical measures to ensure security of personal data including protection against unauthorized access, accidental loss, destruction, or damage.',
 'To protect personal data through appropriate technical security.',
 'Implement encryption at rest and in transit, access controls, intrusion detection, vulnerability management, and security monitoring. Conduct regular security testing.',
 'critical', 98, true,
 'Evaluate technical security measures. Check: 1) Is encryption implemented appropriately? 2) Are access controls in place? 3) Is there security monitoring? 4) Are vulnerabilities managed? 5) Is there intrusion detection?'),

('GDPR-5.1.f-2', 'gdpr', '5.1.f.2', 'Principles', 'Security',
 'Organizational Security Measures',
 'Implement organizational measures including policies, procedures, training, and governance to protect personal data.',
 'To ensure organizational practices protect personal data.',
 'Develop and enforce security policies. Conduct regular staff training. Implement security governance including risk assessment and incident response.',
 'critical', 97, true,
 'Assess organizational security. Verify: 1) Are security policies documented and enforced? 2) Is there regular security training? 3) Is there security governance? 4) Are risks regularly assessed?'),

-- Accountability (Art 5.2)
('GDPR-5.2-1', 'gdpr', '5.2.1', 'Principles', 'Accountability',
 'Compliance Demonstration',
 'Maintain documentation and evidence demonstrating compliance with all data protection principles. Be able to demonstrate compliance to supervisory authorities.',
 'To demonstrate accountability for GDPR compliance.',
 'Implement a compliance management system with documentation, policies, procedures, training records, assessments, and audit trails. Conduct regular compliance reviews.',
 'critical', 96, true,
 'Evaluate accountability mechanisms. Check: 1) Is there comprehensive compliance documentation? 2) Can compliance be demonstrated on request? 3) Are there regular compliance reviews? 4) Is there an audit trail of compliance activities?'),

-- Article 6: Lawfulness of Processing
('GDPR-6.1-1', 'gdpr', '6.1.1', 'Lawfulness', 'Legal Basis',
 'Legitimate Interests Assessment',
 'Conduct and document Legitimate Interests Assessments (LIA) when relying on legitimate interests as the legal basis, balancing controller interests against data subject rights.',
 'To ensure legitimate interests processing is properly justified.',
 'Create LIA template covering: purpose, necessity, balancing test, safeguards. Conduct LIA before processing begins. Document outcomes and review when circumstances change.',
 'high', 94, false,
 'Assess legitimate interests processing. Verify: 1) Are LIAs conducted before processing? 2) Is the three-part test applied (purpose, necessity, balance)? 3) Are LIAs documented? 4) Are safeguards identified?'),

('GDPR-6.1-2', 'gdpr', '6.1.2', 'Lawfulness', 'Legal Basis',
 'Contract Necessity Assessment',
 'When processing is based on contractual necessity, ensure the processing is genuinely necessary to perform the contract, not merely useful or permitted by contract terms.',
 'To correctly apply the contract legal basis.',
 'Map contract-based processing to specific contract obligations. Distinguish between processing necessary for performance versus processing merely authorized by contract. Document assessments.',
 'high', 92, false,
 'Evaluate contract basis processing. Check: 1) Is processing genuinely necessary for contract performance? 2) Is processing mapped to specific contract obligations? 3) Is optional processing identified separately? 4) Are assessments documented?'),

-- Article 7: Conditions for Consent
('GDPR-7.1', 'gdpr', '7.1', 'Consent', 'Demonstration',
 'Consent Evidence Retention',
 'Maintain evidence of consent including who consented, when, how, what they were told, and whether consent has been withdrawn.',
 'To demonstrate that valid consent was obtained.',
 'Store consent records with: timestamp, identity verification, consent text/version, method of consent, IP/device info, withdrawal status. Retain for duration of processing plus legal limitation period.',
 'critical', 95, true,
 'Assess consent record keeping. Verify: 1) Are consent records retained? 2) Do records include who, when, how, and what? 3) Is withdrawal status tracked? 4) Are records retained appropriately?'),

('GDPR-7.2', 'gdpr', '7.2', 'Consent', 'Request',
 'Consent Request Clarity',
 'Present consent requests in a clearly distinguishable manner, using clear and plain language, separate from other matters.',
 'To ensure consent requests are clear and not bundled with other terms.',
 'Design consent interfaces with clear language, separate from T&Cs. Avoid pre-ticked boxes. Use layered information for complex processing. Test consent forms for readability.',
 'high', 93, true,
 'Evaluate consent request design. Check: 1) Is consent clearly distinguishable from other matters? 2) Is plain language used? 3) Are pre-ticked boxes avoided? 4) Is information layered appropriately?'),

('GDPR-7.3', 'gdpr', '7.3', 'Consent', 'Withdrawal',
 'Easy Consent Withdrawal',
 'Provide mechanisms for withdrawing consent that are as easy as giving consent. Inform data subjects of the right to withdraw before obtaining consent.',
 'To enable and facilitate consent withdrawal.',
 'Implement self-service consent withdrawal (same channel as consent given). Process withdrawals promptly. Stop processing immediately upon withdrawal unless another legal basis applies.',
 'critical', 96, true,
 'Assess consent withdrawal. Verify: 1) Is withdrawal as easy as giving consent? 2) Are data subjects informed of withdrawal right? 3) Is withdrawal processed promptly? 4) Does processing stop after withdrawal?'),

-- Article 8: Child Consent
('GDPR-8.1', 'gdpr', '8.1', 'Consent', 'Children',
 'Age Verification for Children',
 'Implement age verification mechanisms when offering information society services directly to children. Obtain parental consent for children under applicable age threshold.',
 'To protect children and obtain valid consent for their data processing.',
 'Implement age gates at registration. Where child identified, obtain parental/guardian consent. Make reasonable efforts to verify parental relationship. Document verification process.',
 'high', 91, true,
 'Evaluate child protection measures. Check: 1) Is age verification implemented? 2) Is parental consent obtained for children? 3) Are reasonable verification efforts made? 4) Is the process documented?'),

-- Article 9: Special Category Data
('GDPR-9.1', 'gdpr', '9.1', 'Special Categories', 'Processing Conditions',
 'Special Category Data Identification',
 'Identify and document all processing of special category data (racial origin, political opinions, religious beliefs, health, sex life, biometric, genetic data).',
 'To ensure special category data receives enhanced protection.',
 'Conduct data mapping to identify special category data. Tag and classify accordingly. Implement enhanced access controls and monitoring for special category data.',
 'critical', 97, true,
 'Assess special category data handling. Verify: 1) Is special category data identified? 2) Is it documented in processing registers? 3) Are enhanced controls in place? 4) Is there a valid Article 9 exemption?'),

('GDPR-9.2', 'gdpr', '9.2.1', 'Special Categories', 'Explicit Consent',
 'Explicit Consent for Special Categories',
 'When processing special category data based on consent, ensure consent is explicit - a clear affirmative statement, not inferred from conduct.',
 'To obtain valid explicit consent for special category data.',
 'Require explicit consent statements for special category data. Use checkboxes with clear text, signature confirmation, or recorded verbal consent. Never rely on implied consent.',
 'critical', 95, true,
 'Evaluate explicit consent for special categories. Check: 1) Is consent explicit (not implied)? 2) Is there a clear affirmative statement? 3) Is the consent specific to the special category processing? 4) Is consent recorded?'),

-- Article 10: Criminal Conviction Data
('GDPR-10.1', 'gdpr', '10.1', 'Criminal Data', 'Processing',
 'Criminal Data Processing Authorization',
 'Process criminal conviction and offense data only under official authority control or when authorized by Union or Member State law providing appropriate safeguards.',
 'To ensure criminal data processing has proper authorization.',
 'Identify all criminal data processing. Verify legal authority or authorization. Implement safeguards specified in applicable law. Maintain separate register of criminal data processing.',
 'critical', 93, true,
 'Assess criminal data processing. Verify: 1) Is there official authority or legal authorization? 2) Are required safeguards implemented? 3) Is processing registered? 4) Are access controls enhanced?'),

-- Article 11: Processing Not Requiring Identification
('GDPR-11.1', 'gdpr', '11.1', 'Identification', 'Non-identification',
 'Identification Avoidance',
 'Where purposes do not require data subject identification, do not maintain, acquire, or process additional information solely to identify data subjects.',
 'To minimize identification where not necessary.',
 'Assess whether identification is necessary for each processing purpose. Use anonymization or pseudonymization where identification not required. Do not create identification capability solely to respond to rights requests.',
 'medium', 85, false,
 'Evaluate identification practices. Check: 1) Is identification necessity assessed? 2) Are there processes avoiding unnecessary identification? 3) Is anonymization/pseudonymization used where appropriate?'),

-- ============================================================================
-- CHAPTER III: RIGHTS OF THE DATA SUBJECT (Articles 12-23) - 44 Controls
-- ============================================================================

-- Article 12: Transparent Information
('GDPR-12.1', 'gdpr', '12.1', 'Transparency', 'Communication',
 'Accessible Communication',
 'Provide information relating to processing in a concise, transparent, intelligible, and easily accessible form, using clear and plain language.',
 'To ensure data subjects can understand how their data is processed.',
 'Use plain language in all communications. Avoid legal jargon. Provide information in layered format. Test readability. Offer multiple formats for accessibility.',
 'high', 94, true,
 'Assess communication accessibility. Verify: 1) Is language clear and plain? 2) Is information concise and accessible? 3) Are different formats available? 4) Is readability tested?'),

('GDPR-12.2', 'gdpr', '12.2', 'Transparency', 'Facilitation',
 'Rights Exercise Facilitation',
 'Facilitate the exercise of data subject rights. Do not obstruct or discourage rights exercise.',
 'To enable data subjects to effectively exercise their rights.',
 'Create clear rights exercise procedures. Provide multiple channels for requests. Do not impose unnecessary barriers or fees. Train staff on handling requests.',
 'critical', 96, true,
 'Evaluate rights facilitation. Check: 1) Are there clear procedures for rights exercise? 2) Are multiple channels available? 3) Are there unnecessary barriers? 4) Is staff trained?'),

('GDPR-12.3', 'gdpr', '12.3', 'Transparency', 'Response Time',
 'Rights Request Response Timeline',
 'Respond to data subject requests without undue delay and within one month. Extensions up to two additional months may apply for complex requests with notification.',
 'To ensure timely response to data subject rights requests.',
 'Implement tracking system for rights requests with SLA monitoring. Create escalation procedures for complex requests. Automate response timeline notifications.',
 'critical', 98, true,
 'Assess response timeline compliance. Verify: 1) Are responses provided within one month? 2) Are extensions properly notified? 3) Is there request tracking? 4) Are SLAs monitored?'),

('GDPR-12.4', 'gdpr', '12.4', 'Transparency', 'Free of Charge',
 'No Fee for Rights Exercise',
 'Provide information and exercise of rights free of charge. Fees only permissible for manifestly unfounded or excessive requests.',
 'To ensure rights are not restricted by cost.',
 'Process all rights requests free of charge by default. Document criteria for manifestly unfounded/excessive requests. Maintain records when fees are charged with justification.',
 'high', 92, true,
 'Evaluate fee practices. Check: 1) Are rights exercised free of charge? 2) Are fee criteria documented? 3) Are fee decisions justified? 4) Are records maintained?'),

('GDPR-12.5', 'gdpr', '12.5', 'Transparency', 'Identity Verification',
 'Requester Identity Verification',
 'Verify the identity of data subjects making rights requests to prevent unauthorized disclosure. Do not require excessive identification.',
 'To balance identity verification with access facilitation.',
 'Implement proportionate identity verification. Use existing authentication where available. Do not request more identification than necessary. Document verification procedures.',
 'high', 93, true,
 'Assess identity verification. Verify: 1) Is verification proportionate? 2) Are existing authentication mechanisms used? 3) Is excessive identification avoided? 4) Are procedures documented?'),

-- Article 13: Information at Collection
('GDPR-13.1', 'gdpr', '13.1', 'Information Provision', 'Direct Collection',
 'Controller Identity Disclosure',
 'Provide the identity and contact details of the controller (and representative where applicable) at the time of data collection.',
 'To ensure data subjects know who is responsible for their data.',
 'Include full controller identity and contact information in all privacy notices and collection points. Keep information current.',
 'critical', 97, true,
 'Verify controller identity disclosure. Check: 1) Is controller identity provided? 2) Are contact details included? 3) Is representative information provided where applicable? 4) Is information current?'),

('GDPR-13.2', 'gdpr', '13.2', 'Information Provision', 'Direct Collection',
 'DPO Contact Disclosure',
 'Provide contact details of the Data Protection Officer where one is designated.',
 'To enable data subjects to contact the DPO.',
 'Include DPO contact details in privacy notices and make easily accessible. Ensure DPO contact mechanism is functional.',
 'high', 91, true,
 'Verify DPO contact disclosure. Check: 1) Are DPO contact details provided? 2) Are they easily accessible? 3) Is the contact mechanism functional?'),

('GDPR-13.3', 'gdpr', '13.3', 'Information Provision', 'Direct Collection',
 'Purpose and Legal Basis Disclosure',
 'Inform data subjects of the purposes of processing and the legal basis for each purpose at the time of collection.',
 'To ensure data subjects understand why their data is processed.',
 'List all processing purposes with corresponding legal bases in privacy notices. Map to processing register. Keep synchronized.',
 'critical', 96, true,
 'Assess purpose/basis disclosure. Verify: 1) Are all purposes disclosed? 2) Is the legal basis for each purpose stated? 3) Is legitimate interests reasoning provided? 4) Is information synchronized with processing register?'),

('GDPR-13.4', 'gdpr', '13.4', 'Information Provision', 'Direct Collection',
 'Legitimate Interests Disclosure',
 'Where processing is based on legitimate interests, provide information about those interests.',
 'To enable data subjects to understand and challenge legitimate interests.',
 'Describe legitimate interests in privacy notices. Explain why processing is necessary for those interests. Link to LIA where appropriate.',
 'high', 90, false,
 'Evaluate legitimate interests disclosure. Check: 1) Are legitimate interests explained? 2) Is the necessity described? 3) Is balancing test outcome communicated?'),

('GDPR-13.5', 'gdpr', '13.5', 'Information Provision', 'Direct Collection',
 'Recipient Disclosure',
 'Provide information about recipients or categories of recipients of personal data.',
 'To enable data subjects to understand data sharing.',
 'List recipients or recipient categories in privacy notices. Include third parties, processors, and intra-group transfers. Keep recipient list current.',
 'high', 92, true,
 'Assess recipient disclosure. Verify: 1) Are recipients or categories disclosed? 2) Are processors included? 3) Are third parties identified? 4) Is information current?'),

('GDPR-13.6', 'gdpr', '13.6', 'Information Provision', 'Direct Collection',
 'Transfer Disclosure',
 'Inform data subjects of any intention to transfer personal data to a third country, the existence or absence of an adequacy decision, and applicable safeguards.',
 'To ensure transparency about international transfers.',
 'Disclose international transfers in privacy notices with: destination countries, adequacy decision status, safeguards used (SCCs, BCRs, etc.), means to obtain copy of safeguards.',
 'high', 93, true,
 'Evaluate transfer disclosure. Check: 1) Are transfers disclosed? 2) Is adequacy decision status stated? 3) Are safeguards identified? 4) Can safeguard copies be obtained?'),

('GDPR-13.7', 'gdpr', '13.7', 'Information Provision', 'Direct Collection',
 'Retention Period Disclosure',
 'Provide the storage period or criteria used to determine the period.',
 'To inform data subjects how long their data will be kept.',
 'Include retention periods or criteria in privacy notices for each category of data/purpose. Link to retention schedule.',
 'high', 91, true,
 'Assess retention disclosure. Verify: 1) Are retention periods disclosed? 2) If not specific periods, are criteria explained? 3) Does disclosure cover all data categories?'),

('GDPR-13.8', 'gdpr', '13.8', 'Information Provision', 'Direct Collection',
 'Rights Information',
 'Inform data subjects of their rights: access, rectification, erasure, restriction, objection, portability, and complaint to supervisory authority.',
 'To ensure data subjects know their rights.',
 'Include comprehensive rights information in privacy notices. Explain how to exercise each right. Provide supervisory authority contact details.',
 'critical', 95, true,
 'Evaluate rights information. Check: 1) Are all applicable rights listed? 2) Is information on exercising rights provided? 3) Is complaint right and SA contact included?'),

('GDPR-13.9', 'gdpr', '13.9', 'Information Provision', 'Direct Collection',
 'Consent Withdrawal Information',
 'Where processing is based on consent, inform of the right to withdraw consent at any time without affecting the lawfulness of processing before withdrawal.',
 'To ensure data subjects know they can withdraw consent.',
 'Include withdrawal right information prominently in consent requests and privacy notices. Explain how to withdraw.',
 'high', 93, true,
 'Verify withdrawal information. Check: 1) Is withdrawal right communicated? 2) Is it provided before or at time of consent? 3) Is the withdrawal process explained?'),

('GDPR-13.10', 'gdpr', '13.10', 'Information Provision', 'Direct Collection',
 'Statutory/Contractual Requirement Disclosure',
 'Inform whether provision of personal data is a statutory or contractual requirement, whether the data subject is obliged to provide data, and consequences of failure to provide.',
 'To ensure data subjects understand obligation and consequences.',
 'Clearly indicate mandatory versus optional data fields. Explain consequences of not providing data. State statutory or contractual basis for mandatory requirements.',
 'medium', 88, true,
 'Assess requirement disclosure. Verify: 1) Is mandatory/optional status clear? 2) Are consequences of non-provision explained? 3) Is statutory/contractual basis stated?'),

('GDPR-13.11', 'gdpr', '13.11', 'Information Provision', 'Direct Collection',
 'Automated Decision-Making Disclosure',
 'Where automated decision-making including profiling exists, provide meaningful information about the logic involved, significance, and envisaged consequences.',
 'To ensure transparency about automated decisions.',
 'Identify all automated decision-making with legal/significant effects. Provide meaningful explanation of logic, significance, and consequences in accessible language.',
 'high', 94, true,
 'Evaluate automated decision disclosure. Check: 1) Is automated decision-making identified? 2) Is logic explained meaningfully? 3) Are significance and consequences described?'),

-- Article 14: Information Where Data Not Obtained from Data Subject
('GDPR-14.1', 'gdpr', '14.1', 'Information Provision', 'Indirect Collection',
 'Source Disclosure',
 'When personal data is not obtained from the data subject, provide information about the source of data including whether it came from publicly accessible sources.',
 'To ensure transparency when data is obtained indirectly.',
 'Track and document data sources. Include source information in privacy notices. Notify data subjects of source when providing required information.',
 'high', 90, true,
 'Assess source disclosure. Verify: 1) Are data sources tracked? 2) Is source information provided to data subjects? 3) Are public sources identified?'),

('GDPR-14.2', 'gdpr', '14.2', 'Information Provision', 'Indirect Collection',
 'Indirect Collection Notification Timeline',
 'Provide required information within a reasonable period after obtaining data (maximum one month), at first communication, or when first disclosing to another recipient.',
 'To ensure timely notification of indirect data collection.',
 'Implement processes to notify data subjects within required timeframes. Track notification deadlines. Document notification delivery.',
 'high', 91, true,
 'Evaluate notification timing. Check: 1) Is notification within one month? 2) Is notification at first communication? 3) Is notification before first third-party disclosure? 4) Is timing documented?'),

('GDPR-14.3', 'gdpr', '14.3', 'Information Provision', 'Indirect Collection',
 'Categories of Data Disclosure',
 'When data is obtained indirectly, inform data subjects of the categories of personal data concerned.',
 'To ensure data subjects know what types of data are held about them.',
 'Document categories of indirectly obtained data. Include in privacy notices. Be specific about data types.',
 'medium', 87, true,
 'Verify category disclosure. Check: 1) Are data categories specified? 2) Are categories sufficiently specific? 3) Is this provided when data not obtained directly?'),

-- Article 15: Right of Access
('GDPR-15.1', 'gdpr', '15.1', 'Data Subject Rights', 'Access',
 'Access Request Processing',
 'Provide data subjects with confirmation of whether personal data is being processed and, where it is, access to the personal data and specified information.',
 'To enable data subjects to access their personal data.',
 'Implement subject access request (SAR) process. Search all systems for requester data. Compile response with required information. Provide within one month.',
 'critical', 98, true,
 'Assess access request handling. Verify: 1) Is there a SAR process? 2) Are all systems searched? 3) Is data provided with required information? 4) Is the one-month deadline met?'),

('GDPR-15.2', 'gdpr', '15.2', 'Data Subject Rights', 'Access',
 'Access Information Completeness',
 'Provide with access: purposes, categories, recipients, retention periods, rights information, source, and automated decision-making details.',
 'To ensure complete information accompanies data access.',
 'Create SAR response template including all required elements. Verify completeness before sending. Document what was provided.',
 'high', 93, true,
 'Evaluate access response completeness. Check all required elements: 1) Purposes 2) Categories 3) Recipients 4) Retention 5) Rights 6) Source 7) Automated decisions'),

('GDPR-15.3', 'gdpr', '15.3', 'Data Subject Rights', 'Access',
 'Copy of Personal Data',
 'Provide a copy of personal data undergoing processing. Provide in commonly used electronic form if requested electronically.',
 'To provide data in usable format.',
 'Generate data exports in structured, commonly used format. For electronic requests, provide electronically. Enable secure download mechanism.',
 'high', 92, true,
 'Assess data copy provision. Verify: 1) Is a copy provided? 2) Is format commonly used and structured? 3) Is electronic format used for electronic requests?'),

('GDPR-15.4', 'gdpr', '15.4', 'Data Subject Rights', 'Access',
 'Third-Party Rights Protection',
 'Ensure the right of access does not adversely affect the rights and freedoms of others including trade secrets and intellectual property.',
 'To balance access rights with other legitimate interests.',
 'Review access responses for third-party data. Redact where necessary to protect others. Document balancing decisions.',
 'medium', 86, false,
 'Evaluate third-party protection. Check: 1) Is third-party data identified? 2) Is redaction applied appropriately? 3) Are balancing decisions documented?'),

-- Article 16: Right to Rectification
('GDPR-16.1', 'gdpr', '16.1', 'Data Subject Rights', 'Rectification',
 'Rectification Request Processing',
 'Enable data subjects to obtain rectification of inaccurate personal data without undue delay.',
 'To correct inaccurate personal data promptly.',
 'Implement rectification request workflow. Verify accuracy of correction request. Update all systems containing the data. Confirm completion to data subject.',
 'high', 94, true,
 'Assess rectification process. Verify: 1) Is there a rectification workflow? 2) Are corrections verified? 3) Are all systems updated? 4) Is confirmation provided?'),

('GDPR-16.2', 'gdpr', '16.2', 'Data Subject Rights', 'Rectification',
 'Incomplete Data Completion',
 'Enable data subjects to have incomplete personal data completed, including by providing a supplementary statement.',
 'To ensure data completeness when requested.',
 'Accept completion requests. Allow supplementary statements. Integrate completed data into records.',
 'medium', 88, true,
 'Evaluate completion handling. Check: 1) Can completion be requested? 2) Are supplementary statements accepted? 3) Is completed data integrated?'),

-- Article 17: Right to Erasure
('GDPR-17.1', 'gdpr', '17.1', 'Data Subject Rights', 'Erasure',
 'Erasure Request Processing',
 'Erase personal data without undue delay where: consent withdrawn, data no longer necessary, objection upheld, unlawful processing, legal obligation, or child data for ISS.',
 'To enable effective exercise of the right to erasure.',
 'Implement erasure request workflow with grounds verification. Delete from all systems including backups. Document erasure completion. Manage exceptions.',
 'critical', 97, true,
 'Assess erasure process. Verify: 1) Are grounds verified? 2) Is erasure from all systems? 3) Are backups addressed? 4) Is completion documented? 5) Are exceptions managed?'),

('GDPR-17.2', 'gdpr', '17.2', 'Data Subject Rights', 'Erasure',
 'Erasure Notification to Recipients',
 'Where data has been made public, take reasonable steps to inform other controllers processing the data about the erasure request.',
 'To facilitate complete erasure across controllers.',
 'Track public disclosures. Notify known recipients of erasure. Document notification attempts and outcomes.',
 'high', 90, true,
 'Evaluate recipient notification. Check: 1) Are disclosures tracked? 2) Are recipients notified? 3) Are reasonable steps documented?'),

('GDPR-17.3', 'gdpr', '17.3', 'Data Subject Rights', 'Erasure',
 'Erasure Exceptions Management',
 'Document and apply exceptions to erasure: freedom of expression, legal obligation, public health, archiving/research, and legal claims.',
 'To properly manage erasure exceptions.',
 'Assess each erasure request against exceptions. Document exception basis. Retain only what exception allows. Inform data subject of exception applied.',
 'high', 91, true,
 'Assess exception handling. Verify: 1) Are exceptions assessed? 2) Is the basis documented? 3) Is retention limited to exception scope? 4) Is data subject informed?'),

-- Article 18: Right to Restriction
('GDPR-18.1', 'gdpr', '18.1', 'Data Subject Rights', 'Restriction',
 'Restriction Request Processing',
 'Enable restriction of processing where: accuracy contested, processing unlawful, no longer needed but required for legal claims, or pending objection verification.',
 'To enable effective restriction of processing.',
 'Implement restriction request workflow. Verify grounds. Apply technical restriction mechanisms. Maintain data but prevent processing except storage.',
 'high', 92, true,
 'Assess restriction process. Verify: 1) Are grounds verified? 2) Is technical restriction implemented? 3) Is processing limited to storage? 4) Are exceptions managed?'),

('GDPR-18.2', 'gdpr', '18.2', 'Data Subject Rights', 'Restriction',
 'Restriction Lifting Notification',
 'Inform the data subject before lifting a restriction on processing.',
 'To ensure data subjects are aware when restriction ends.',
 'Track restriction status. Notify before lifting restriction. Document notification.',
 'medium', 87, true,
 'Evaluate lifting notification. Check: 1) Is restriction status tracked? 2) Is notification provided before lifting? 3) Is notification documented?'),

-- Article 19: Notification Obligation
('GDPR-19.1', 'gdpr', '19.1', 'Data Subject Rights', 'Notification',
 'Recipient Notification of Actions',
 'Communicate any rectification, erasure, or restriction to each recipient to whom data was disclosed, unless impossible or involves disproportionate effort.',
 'To ensure rectification/erasure/restriction is propagated.',
 'Maintain recipient disclosure records. Notify recipients of actions. Document notifications and any impossibility/disproportionality assessments.',
 'high', 91, true,
 'Assess recipient notification. Verify: 1) Are recipients tracked? 2) Are notifications sent? 3) Is disproportionality assessed? 4) Is impossibility documented?'),

('GDPR-19.2', 'gdpr', '19.2', 'Data Subject Rights', 'Notification',
 'Recipient Information Provision',
 'Inform data subjects about recipients when requested.',
 'To enable data subjects to know who received their data.',
 'Maintain accessible recipient records. Respond to recipient information requests. Include in access request responses.',
 'medium', 85, true,
 'Evaluate recipient information. Check: 1) Are recipient records maintained? 2) Can information be provided on request? 3) Is it included in SAR responses?'),

-- Article 20: Right to Data Portability
('GDPR-20.1', 'gdpr', '20.1', 'Data Subject Rights', 'Portability',
 'Portability Request Processing',
 'Provide personal data in a structured, commonly used, machine-readable format where processing is based on consent or contract and is automated.',
 'To enable data portability between services.',
 'Implement portability export functionality. Use interoperable formats (JSON, CSV, XML). Include all provided and observed data within scope.',
 'high', 93, true,
 'Assess portability implementation. Verify: 1) Is export in structured format? 2) Is format machine-readable? 3) Is format commonly used? 4) Is all qualifying data included?'),

('GDPR-20.2', 'gdpr', '20.2', 'Data Subject Rights', 'Portability',
 'Direct Transfer to Another Controller',
 'Where technically feasible, transmit personal data directly to another controller at the data subject''s request.',
 'To facilitate seamless data transfer between controllers.',
 'Develop API or secure transfer mechanism. Verify receiving controller identity. Document transfer requests and completions.',
 'medium', 84, true,
 'Evaluate direct transfer capability. Check: 1) Is direct transfer possible? 2) Is receiving controller verified? 3) Is transfer documented?'),

-- Article 21: Right to Object
('GDPR-21.1', 'gdpr', '21.1', 'Data Subject Rights', 'Objection',
 'Objection Request Processing',
 'Stop processing personal data for direct marketing immediately upon objection. For other processing, stop unless compelling legitimate grounds override.',
 'To enable effective exercise of the right to object.',
 'Implement objection request workflow. For marketing: stop immediately without assessment. For other purposes: assess compelling grounds. Document outcomes.',
 'critical', 96, true,
 'Assess objection handling. Verify: 1) Is marketing processing stopped immediately? 2) Are compelling grounds assessed for other processing? 3) Are outcomes documented?'),

('GDPR-21.2', 'gdpr', '21.2', 'Data Subject Rights', 'Objection',
 'Objection Right Notification',
 'Explicitly bring the right to object to attention of data subject, presenting it clearly and separately from other information, at latest at first communication.',
 'To ensure data subjects are aware of their right to object.',
 'Include right to object prominently in communications. Separate from other information. Present at first communication for marketing.',
 'high', 92, true,
 'Evaluate objection notification. Check: 1) Is right presented clearly? 2) Is it separate from other information? 3) Is it provided at first communication?'),

('GDPR-21.3', 'gdpr', '21.3', 'Data Subject Rights', 'Objection',
 'Research/Statistics Objection Handling',
 'For scientific/historical research or statistics processing, allow objection except where processing is necessary for public interest task.',
 'To properly manage objections to research processing.',
 'Assess research objections against public interest exception. Document assessments. Stop processing unless exception applies.',
 'medium', 83, false,
 'Assess research objection handling. Verify: 1) Are objections assessed? 2) Is public interest exception applied correctly? 3) Are decisions documented?'),

-- Article 22: Automated Individual Decision-Making
('GDPR-22.1', 'gdpr', '22.1', 'Automated Decisions', 'Rights',
 'Automated Decision Restriction',
 'Do not subject data subjects to decisions based solely on automated processing with legal or similarly significant effects, except where authorized by contract, law, or explicit consent.',
 'To protect data subjects from harmful automated decisions.',
 'Identify all solely automated decisions with significant effects. Verify authorization basis. Implement human review where required.',
 'critical', 95, true,
 'Assess automated decision restrictions. Verify: 1) Are solely automated decisions identified? 2) Is authorization verified? 3) Is human review implemented where required?'),

('GDPR-22.2', 'gdpr', '22.2', 'Automated Decisions', 'Safeguards',
 'Automated Decision Safeguards',
 'Implement suitable safeguards for permitted automated decisions: right to obtain human intervention, express views, and contest the decision.',
 'To ensure safeguards for permitted automated decisions.',
 'Provide mechanism for human intervention requests. Enable view expression. Implement contestation procedure. Train review staff.',
 'high', 93, true,
 'Evaluate automated decision safeguards. Check: 1) Is human intervention available? 2) Can views be expressed? 3) Can decisions be contested? 4) Is staff trained?'),

('GDPR-22.3', 'gdpr', '22.3', 'Automated Decisions', 'Special Categories',
 'Automated Decisions on Special Categories',
 'Do not use special category data in automated decisions unless explicit consent given or necessary for substantial public interest with suitable safeguards.',
 'To protect special category data in automated decisions.',
 'Identify automated decisions using special category data. Verify explicit consent or public interest basis. Implement enhanced safeguards.',
 'critical', 94, true,
 'Assess special category automated decisions. Verify: 1) Is special category use identified? 2) Is authorization verified? 3) Are enhanced safeguards in place?'),

-- ============================================================================
-- CHAPTER IV: CONTROLLER AND PROCESSOR (Articles 24-43) - 58 Controls
-- ============================================================================

-- Article 24: Responsibility of Controller
('GDPR-24.1', 'gdpr', '24.1', 'Governance', 'Controller Responsibility',
 'Appropriate Measures Implementation',
 'Implement appropriate technical and organizational measures to ensure and demonstrate processing complies with GDPR, taking into account nature, scope, context, purposes, and risks.',
 'To establish controller accountability.',
 'Conduct processing impact assessment. Implement controls proportionate to risk. Document measures. Review and update regularly.',
 'critical', 97, true,
 'Assess controller measures. Verify: 1) Are measures appropriate to risk? 2) Is nature/scope/context/purpose considered? 3) Are measures documented? 4) Are they regularly reviewed?'),

('GDPR-24.2', 'gdpr', '24.2', 'Governance', 'Controller Responsibility',
 'Data Protection Policy Implementation',
 'Where proportionate, implement appropriate data protection policies.',
 'To formalize data protection practices.',
 'Develop comprehensive data protection policy. Communicate to all staff. Train on policy requirements. Review and update annually.',
 'high', 94, true,
 'Evaluate data protection policy. Check: 1) Is policy documented? 2) Is it communicated to staff? 3) Is training provided? 4) Is it regularly reviewed?'),

-- Article 25: Data Protection by Design and Default
('GDPR-25.1', 'gdpr', '25.1', 'Design', 'Privacy by Design',
 'Data Protection by Design',
 'Implement data protection principles through technical and organizational measures at the time of determining processing means and at time of processing itself.',
 'To embed data protection into processing from the outset.',
 'Include data protection requirements in system design. Conduct privacy impact assessment at design stage. Use privacy-enhancing technologies. Document design decisions.',
 'critical', 96, true,
 'Assess privacy by design. Verify: 1) Are DP requirements in design specs? 2) Is PIA conducted at design stage? 3) Are PETs used? 4) Are decisions documented?'),

('GDPR-25.2', 'gdpr', '25.2.1', 'Design', 'Privacy by Default',
 'Data Minimization by Default',
 'Ensure by default only personal data necessary for each specific purpose is processed (amount, extent, storage period, accessibility).',
 'To minimize data processing by default.',
 'Configure systems to collect minimum data by default. Set shortest retention by default. Limit access by default. Require justification for expansion.',
 'high', 93, true,
 'Evaluate default settings. Check: 1) Is minimum data collected by default? 2) Is retention shortest by default? 3) Is access restricted by default? 4) Is expansion justified?'),

('GDPR-25.3', 'gdpr', '25.2.2', 'Design', 'Privacy by Default',
 'Default Accessibility Restriction',
 'Ensure by default personal data is not made accessible without individual intervention to an indefinite number of persons.',
 'To prevent uncontrolled data access by default.',
 'Configure data as private by default. Require explicit action to share or publish. Log accessibility changes.',
 'high', 91, true,
 'Assess default accessibility. Verify: 1) Is data private by default? 2) Is explicit action required to share? 3) Are accessibility changes logged?'),

-- Article 26: Joint Controllers
('GDPR-26.1', 'gdpr', '26.1', 'Governance', 'Joint Controllers',
 'Joint Controller Arrangement',
 'Where two or more controllers jointly determine purposes and means, document respective responsibilities in a transparent arrangement.',
 'To clearly define joint controller responsibilities.',
 'Identify joint controller relationships. Document arrangement covering: respective responsibilities, DPO contact, data subject interface, liability allocation.',
 'high', 90, true,
 'Assess joint controller arrangements. Verify: 1) Is joint controllership identified? 2) Is arrangement documented? 3) Are responsibilities clear? 4) Is data subject contact defined?'),

('GDPR-26.2', 'gdpr', '26.2', 'Governance', 'Joint Controllers',
 'Joint Controller Essence Availability',
 'Make the essence of the joint controller arrangement available to data subjects.',
 'To provide transparency about joint controller relationships.',
 'Summarize key points of arrangement for data subjects. Include in privacy notices. Make available on request.',
 'medium', 86, true,
 'Evaluate essence availability. Check: 1) Is essence summarized? 2) Is it available in privacy notices? 3) Is it accessible to data subjects?'),

-- Article 27: Representatives
('GDPR-27.1', 'gdpr', '27.1', 'Governance', 'Representatives',
 'EU Representative Designation',
 'Where controller/processor not established in EU but processes EU data subjects'' data, designate a representative in the Union (with exceptions).',
 'To provide EU presence for non-EU controllers/processors.',
 'Assess whether EU representative is required. Designate representative in appropriate Member State. Document representative details. Inform supervisory authorities.',
 'high', 89, true,
 'Assess representative requirement. Verify: 1) Is requirement assessed? 2) Is representative designated if required? 3) Are details documented? 4) Are SAs informed?'),

-- Article 28: Processor
('GDPR-28.1', 'gdpr', '28.1', 'Processing', 'Processor Selection',
 'Processor Due Diligence',
 'Only use processors providing sufficient guarantees to implement appropriate technical and organizational measures.',
 'To ensure processors meet data protection requirements.',
 'Conduct processor due diligence before engagement. Assess security measures and compliance capabilities. Document assessment. Review periodically.',
 'critical', 95, true,
 'Assess processor selection. Verify: 1) Is due diligence conducted? 2) Are guarantees assessed? 3) Is assessment documented? 4) Are periodic reviews conducted?'),

('GDPR-28.2', 'gdpr', '28.2', 'Processing', 'Processor Agreement',
 'Data Processing Agreement',
 'Document processor engagement in a contract or binding act setting out subject-matter, duration, nature, purpose, data type, categories of data subjects, and controller obligations/rights.',
 'To formalize processor relationships.',
 'Use compliant DPA template. Include all required elements. Review and update with processing changes. Maintain signed agreements.',
 'critical', 97, true,
 'Evaluate DPA completeness. Check required elements: 1) Subject-matter 2) Duration 3) Nature/purpose 4) Data types 5) Categories 6) Controller rights/obligations'),

('GDPR-28.3', 'gdpr', '28.3', 'Processing', 'Processor Agreement',
 'Processor Instruction Limitation',
 'Ensure DPA requires processor to process only on documented instructions from controller.',
 'To ensure controller retains control over processing.',
 'Include instruction-only clause in DPA. Document all processing instructions. Monitor compliance with instructions.',
 'high', 93, true,
 'Verify instruction requirement. Check: 1) Is instruction-only clause present? 2) Are instructions documented? 3) Is compliance monitored?'),

('GDPR-28.4', 'gdpr', '28.4', 'Processing', 'Processor Agreement',
 'Processor Confidentiality Obligation',
 'Ensure DPA requires processor to ensure authorized personnel have committed to confidentiality.',
 'To protect data confidentiality at processor.',
 'Include confidentiality clause in DPA. Require evidence of staff confidentiality commitments. Review during audits.',
 'high', 91, true,
 'Assess confidentiality requirement. Verify: 1) Is confidentiality clause present? 2) Are staff commitments required? 3) Is this verified?'),

('GDPR-28.5', 'gdpr', '28.5', 'Processing', 'Processor Agreement',
 'Processor Security Measures',
 'Ensure DPA requires processor to take all measures required under Article 32 (security of processing).',
 'To ensure processor implements appropriate security.',
 'Include Article 32 security requirements in DPA. Specify required security measures. Verify implementation during audits.',
 'critical', 94, true,
 'Evaluate security requirements. Check: 1) Are Article 32 requirements included? 2) Are specific measures identified? 3) Is implementation verified?'),

('GDPR-28.6', 'gdpr', '28.6', 'Processing', 'Sub-processors',
 'Sub-processor Management',
 'Ensure DPA addresses sub-processor engagement: prior authorization requirement, and imposition of same data protection obligations.',
 'To control and monitor sub-processor chain.',
 'Include sub-processor clauses in DPA. Require prior authorization (specific or general). Ensure flow-down of obligations. Maintain sub-processor register.',
 'high', 92, true,
 'Assess sub-processor management. Verify: 1) Is authorization required? 2) Are obligations flowed down? 3) Is there a sub-processor register?'),

('GDPR-28.7', 'gdpr', '28.7', 'Processing', 'Processor Agreement',
 'Processor Assistance Obligations',
 'Ensure DPA requires processor to assist controller with data subject rights requests, security obligations, DPIAs, and prior consultation.',
 'To ensure processor supports controller compliance.',
 'Include assistance clauses for: Article 32-36 obligations, data subject requests, breach notification. Define response times and procedures.',
 'high', 90, true,
 'Evaluate assistance obligations. Check: 1) Is rights request assistance required? 2) Is security assistance required? 3) Is DPIA/consultation assistance required?'),

('GDPR-28.8', 'gdpr', '28.8', 'Processing', 'Processor Agreement',
 'Processor Data Return/Deletion',
 'Ensure DPA requires processor to delete or return all personal data after processing ends and delete existing copies unless storage required by law.',
 'To ensure data disposal at end of processing.',
 'Include deletion/return clause in DPA. Specify timeline. Require deletion certification. Verify during offboarding.',
 'high', 91, true,
 'Assess end-of-processing requirements. Verify: 1) Is deletion/return required? 2) Is timeline specified? 3) Is certification required?'),

('GDPR-28.9', 'gdpr', '28.9', 'Processing', 'Processor Audit',
 'Processor Audit Rights',
 'Ensure DPA provides controller with audit rights to verify processor compliance.',
 'To enable verification of processor compliance.',
 'Include audit clause in DPA. Conduct periodic audits. Review audit reports and attestations. Document findings and remediation.',
 'high', 92, true,
 'Evaluate audit provisions. Check: 1) Is audit right included? 2) Are audits conducted? 3) Are findings documented? 4) Is remediation tracked?'),

-- Article 29: Processing Under Controller Authority
('GDPR-29.1', 'gdpr', '29.1', 'Processing', 'Authorization',
 'Authorized Personnel Control',
 'Ensure persons acting under controller/processor authority who have access to personal data process only on instructions, unless required by law.',
 'To control authorized access to personal data.',
 'Limit data access to authorized personnel. Train on processing limitations. Monitor compliance. Document instructions.',
 'high', 93, true,
 'Assess authorized access control. Verify: 1) Is access limited to authorized personnel? 2) Is training provided? 3) Is compliance monitored?'),

-- Article 30: Records of Processing Activities
('GDPR-30.1', 'gdpr', '30.1', 'Documentation', 'Processing Records',
 'Controller Processing Register',
 'Maintain a record of processing activities containing: controller details, purposes, data subjects, data categories, recipients, transfers, retention, and security measures.',
 'To maintain required processing documentation.',
 'Create and maintain comprehensive ROPA. Include all required elements. Review and update regularly. Keep current.',
 'critical', 96, true,
 'Evaluate controller ROPA. Check required elements: 1) Controller details 2) DPO contact 3) Purposes 4) Categories 5) Recipients 6) Transfers 7) Retention 8) Security'),

('GDPR-30.2', 'gdpr', '30.2', 'Documentation', 'Processing Records',
 'Processor Processing Register',
 'Maintain a record of processing activities on behalf of each controller containing: processor and controller details, processing categories, transfers, and security measures.',
 'To maintain required processor documentation.',
 'Create processor ROPA for each controller relationship. Include all required elements. Synchronize with controller ROPA.',
 'high', 93, true,
 'Evaluate processor ROPA. Check required elements: 1) Processor/controller details 2) Processing categories 3) Transfers 4) Security'),

('GDPR-30.3', 'gdpr', '30.3', 'Documentation', 'Processing Records',
 'ROPA Availability for Supervisory Authority',
 'Make records of processing activities available to supervisory authority on request.',
 'To enable regulatory oversight.',
 'Maintain ROPA in accessible format. Establish process for SA requests. Ensure ROPA is current and complete.',
 'high', 91, true,
 'Assess ROPA availability. Verify: 1) Is ROPA in accessible format? 2) Is there a request process? 3) Is ROPA current?'),

-- Article 32: Security of Processing
('GDPR-32.1', 'gdpr', '32.1', 'Security', 'Appropriate Measures',
 'Risk-Based Security Measures',
 'Implement appropriate technical and organizational security measures considering state of the art, cost, nature, scope, context, purposes, and risk.',
 'To implement appropriate security proportionate to risk.',
 'Conduct security risk assessment. Implement controls proportionate to risk. Consider state of the art. Document security decisions.',
 'critical', 98, true,
 'Assess security measures. Verify: 1) Is risk assessment conducted? 2) Are measures proportionate? 3) Is state of the art considered? 4) Are decisions documented?'),

('GDPR-32.2', 'gdpr', '32.1.a', 'Security', 'Specific Measures',
 'Pseudonymization and Encryption',
 'Implement pseudonymization and encryption of personal data as appropriate.',
 'To protect data through technical measures.',
 'Implement encryption at rest and in transit. Apply pseudonymization where identification not required. Document encryption standards and key management.',
 'high', 94, true,
 'Evaluate encryption/pseudonymization. Check: 1) Is encryption implemented? 2) Is pseudonymization applied appropriately? 3) Is key management documented?'),

('GDPR-32.3', 'gdpr', '32.1.b', 'Security', 'Specific Measures',
 'Confidentiality, Integrity, Availability, Resilience',
 'Ensure ongoing confidentiality, integrity, availability, and resilience of processing systems and services.',
 'To maintain security properties of processing systems.',
 'Implement access controls (confidentiality), integrity checking, high availability, and disaster recovery. Monitor security properties.',
 'critical', 96, true,
 'Assess CIA+R. Verify: 1) Are access controls implemented? 2) Is integrity protected? 3) Is availability maintained? 4) Is there resilience/DR?'),

('GDPR-32.4', 'gdpr', '32.1.c', 'Security', 'Specific Measures',
 'Data Recovery Capability',
 'Ensure ability to restore availability and access to personal data in a timely manner in the event of a physical or technical incident.',
 'To enable data recovery after incidents.',
 'Implement backup and recovery procedures. Test recovery regularly. Define RTOs and RPOs. Document recovery procedures.',
 'high', 93, true,
 'Evaluate recovery capability. Check: 1) Are backups implemented? 2) Is recovery tested? 3) Are RTOs/RPOs defined? 4) Are procedures documented?'),

('GDPR-32.5', 'gdpr', '32.1.d', 'Security', 'Testing',
 'Security Testing and Evaluation',
 'Implement a process for regularly testing, assessing, and evaluating the effectiveness of technical and organizational security measures.',
 'To ensure ongoing security effectiveness.',
 'Conduct regular security testing (penetration tests, vulnerability scans). Assess organizational measures. Evaluate effectiveness. Address findings.',
 'high', 92, true,
 'Assess security testing. Verify: 1) Is regular testing conducted? 2) Are organizational measures assessed? 3) Is effectiveness evaluated? 4) Are findings addressed?'),

('GDPR-32.6', 'gdpr', '32.2', 'Security', 'Risk Assessment',
 'Security Risk Assessment',
 'In assessing appropriate security level, take into account risks including accidental or unlawful destruction, loss, alteration, unauthorized disclosure, or access.',
 'To ensure security addresses relevant risks.',
 'Identify risks to personal data. Assess likelihood and severity. Implement controls addressing identified risks. Document risk assessment.',
 'critical', 95, true,
 'Evaluate security risk assessment. Check: 1) Are risks identified? 2) Are likelihood/severity assessed? 3) Are controls aligned to risks? 4) Is assessment documented?'),

('GDPR-32.7', 'gdpr', '32.4', 'Security', 'Staff Security',
 'Staff Authorization and Instruction',
 'Ensure persons acting under authority of controller/processor who have access to personal data only process on instructions.',
 'To control staff processing of personal data.',
 'Limit access to authorized personnel. Provide clear processing instructions. Monitor compliance. Handle unauthorized processing.',
 'high', 91, true,
 'Assess staff security. Verify: 1) Is access limited to authorized staff? 2) Are instructions provided? 3) Is compliance monitored?'),

-- Article 33: Breach Notification to Supervisory Authority
('GDPR-33.1', 'gdpr', '33.1', 'Breach Management', 'SA Notification',
 'Breach Detection Capability',
 'Implement capability to detect personal data breaches in a timely manner.',
 'To enable timely breach identification.',
 'Deploy breach detection mechanisms. Train staff on recognition. Create reporting channels. Monitor for anomalies.',
 'critical', 96, true,
 'Assess breach detection. Verify: 1) Are detection mechanisms in place? 2) Is staff trained? 3) Are reporting channels clear? 4) Is monitoring implemented?'),

('GDPR-33.2', 'gdpr', '33.1.1', 'Breach Management', 'SA Notification',
 '72-Hour Notification to Supervisory Authority',
 'Notify supervisory authority of personal data breach without undue delay and within 72 hours of becoming aware, unless unlikely to result in risk.',
 'To ensure timely regulatory notification.',
 'Establish 72-hour notification process. Prepare notification template with required elements. Document awareness timing. Train breach response team.',
 'critical', 98, true,
 'Evaluate SA notification process. Verify: 1) Is 72-hour deadline met? 2) Is there a notification process? 3) Is timing documented? 4) Is team trained?'),

('GDPR-33.3', 'gdpr', '33.2', 'Breach Management', 'SA Notification',
 'Risk Likelihood Assessment',
 'Assess whether breach is likely to result in risk to rights and freedoms of natural persons to determine notification requirement.',
 'To properly assess breach notification requirement.',
 'Develop risk assessment methodology. Assess each breach against criteria. Document assessment rationale. Notify unless no risk.',
 'high', 94, true,
 'Assess risk evaluation. Check: 1) Is methodology documented? 2) Is each breach assessed? 3) Is rationale documented? 4) Is default to notify?'),

('GDPR-33.4', 'gdpr', '33.3', 'Breach Management', 'SA Notification',
 'Breach Notification Content',
 'Include in SA notification: breach nature, DPO contact, likely consequences, and measures taken or proposed.',
 'To provide complete breach notification.',
 'Use notification template with all elements. Describe breach categories and numbers. Explain consequences. Detail remediation.',
 'high', 93, true,
 'Evaluate notification content. Check required elements: 1) Breach nature/categories/numbers 2) DPO contact 3) Likely consequences 4) Measures taken/proposed'),

('GDPR-33.5', 'gdpr', '33.4', 'Breach Management', 'SA Notification',
 'Delayed Information Provision',
 'Where information cannot be provided at once, provide in phases without further undue delay.',
 'To allow phased breach notification when necessary.',
 'Allow phased notifications. Update SA as information becomes available. Document updates.',
 'medium', 87, true,
 'Assess phased notification. Verify: 1) Is phased approach available? 2) Are updates provided promptly? 3) Are updates documented?'),

('GDPR-33.6', 'gdpr', '33.5', 'Breach Management', 'Documentation',
 'Breach Documentation',
 'Document all personal data breaches including facts, effects, and remedial action taken.',
 'To maintain breach records for verification.',
 'Create breach register. Document each breach with: facts, timeline, effects, response, remediation. Retain for SA inspection.',
 'critical', 95, true,
 'Evaluate breach documentation. Check: 1) Is breach register maintained? 2) Are facts documented? 3) Are effects recorded? 4) Is remediation tracked?'),

-- Article 34: Breach Notification to Data Subjects
('GDPR-34.1', 'gdpr', '34.1', 'Breach Management', 'DS Notification',
 'High-Risk Breach Notification to Data Subjects',
 'When breach likely to result in high risk to rights and freedoms, communicate the breach to affected data subjects without undue delay.',
 'To ensure data subjects are notified of high-risk breaches.',
 'Assess breaches for high risk. Prepare communication template. Notify affected individuals promptly. Document notifications.',
 'critical', 97, true,
 'Assess DS notification. Verify: 1) Is high risk assessed? 2) Are affected individuals identified? 3) Is notification prompt? 4) Are notifications documented?'),

('GDPR-34.2', 'gdpr', '34.2', 'Breach Management', 'DS Notification',
 'Clear Breach Communication',
 'Describe breach in clear and plain language. Include DPO contact, consequences, and measures including data subject actions.',
 'To provide useful breach information to data subjects.',
 'Use clear language in notifications. Include all required elements. Provide actionable recommendations.',
 'high', 92, true,
 'Evaluate DS communication. Check: 1) Is language clear? 2) Is DPO contact included? 3) Are consequences explained? 4) Are protective measures described?'),

('GDPR-34.3', 'gdpr', '34.3', 'Breach Management', 'DS Notification',
 'Notification Exceptions Assessment',
 'Assess whether notification exceptions apply: encryption/unintelligibility, subsequent measures eliminating risk, or disproportionate effort.',
 'To properly apply DS notification exceptions.',
 'Document exception assessment for each high-risk breach. Apply exceptions narrowly. Use public communication if disproportionate effort.',
 'medium', 88, false,
 'Assess exception application. Verify: 1) Are exceptions assessed? 2) Is assessment documented? 3) Are exceptions applied narrowly? 4) Is public communication used when appropriate?'),

-- Article 35: Data Protection Impact Assessment
('GDPR-35.1', 'gdpr', '35.1', 'Governance', 'DPIA',
 'DPIA Requirement Assessment',
 'Assess whether processing is likely to result in high risk to rights and freedoms requiring a DPIA, particularly for new technologies, profiling, special categories, or systematic monitoring.',
 'To identify when DPIA is required.',
 'Create DPIA screening process. Apply to all new processing. Consider indicative criteria. Document screening outcomes.',
 'high', 94, true,
 'Evaluate DPIA screening. Check: 1) Is screening process established? 2) Is it applied to new processing? 3) Are criteria considered? 4) Are outcomes documented?'),

('GDPR-35.2', 'gdpr', '35.3', 'Governance', 'DPIA',
 'Mandatory DPIA Cases',
 'Conduct DPIA for systematic evaluation of personal aspects (profiling), large-scale processing of special categories, and systematic monitoring of public areas.',
 'To ensure DPIA for mandatory cases.',
 'Identify mandatory DPIA cases. Conduct DPIA before processing begins. Document DPIA. Review when processing changes.',
 'critical', 96, true,
 'Assess mandatory DPIA cases. Verify: 1) Are mandatory cases identified? 2) Is DPIA conducted before processing? 3) Is DPIA documented? 4) Are changes reviewed?'),

('GDPR-35.3', 'gdpr', '35.7', 'Governance', 'DPIA',
 'DPIA Content',
 'Include in DPIA: systematic description of processing, assessment of necessity and proportionality, assessment of risks, and measures to address risks.',
 'To ensure DPIA is comprehensive.',
 'Use DPIA template with all elements. Describe processing systematically. Assess necessity and proportionality. Identify risks and mitigations.',
 'high', 93, true,
 'Evaluate DPIA content. Check: 1) Is processing described systematically? 2) Is necessity/proportionality assessed? 3) Are risks identified? 4) Are mitigations documented?'),

('GDPR-35.4', 'gdpr', '35.9', 'Governance', 'DPIA',
 'Data Subject Views in DPIA',
 'Seek views of data subjects or their representatives in DPIA where appropriate.',
 'To incorporate data subject perspective in impact assessment.',
 'Assess when data subject input is appropriate. Seek views through surveys, consultations, or representatives. Document input received.',
 'medium', 84, false,
 'Assess data subject consultation. Verify: 1) Is appropriateness assessed? 2) Are views sought when appropriate? 3) Is input documented?'),

('GDPR-35.5', 'gdpr', '35.11', 'Governance', 'DPIA',
 'DPIA Review',
 'Review DPIA when there is a change in risk represented by processing operations.',
 'To ensure DPIA remains current.',
 'Trigger DPIA review upon processing changes. Assess risk changes. Update DPIA as necessary. Document reviews.',
 'medium', 86, true,
 'Evaluate DPIA review. Check: 1) Are reviews triggered by changes? 2) Are risk changes assessed? 3) Is DPIA updated? 4) Are reviews documented?'),

-- Article 36: Prior Consultation
('GDPR-36.1', 'gdpr', '36.1', 'Governance', 'Prior Consultation',
 'Prior Consultation Process',
 'Consult supervisory authority before processing where DPIA indicates high risk that cannot be sufficiently mitigated.',
 'To obtain regulatory guidance for high-risk processing.',
 'Establish prior consultation process. Identify when residual risk remains high. Consult SA before proceeding. Document consultation.',
 'high', 89, false,
 'Assess prior consultation. Verify: 1) Is process established? 2) Is high residual risk identified? 3) Is SA consulted when required? 4) Is consultation documented?'),

('GDPR-36.2', 'gdpr', '36.3', 'Governance', 'Prior Consultation',
 'Information for Prior Consultation',
 'Provide SA with: controller/processor responsibilities, purposes and means, measures and safeguards, DPO contact, DPIA, and other requested information.',
 'To support SA prior consultation with required information.',
 'Prepare prior consultation documentation. Include all required elements. Respond to SA information requests.',
 'medium', 85, true,
 'Evaluate consultation information. Check: 1) Is documentation prepared? 2) Are all elements included? 3) Are SA requests addressed?'),

-- Article 37: Designation of DPO
('GDPR-37.1', 'gdpr', '37.1', 'Governance', 'DPO',
 'DPO Designation Requirement',
 'Designate a DPO where processing is by public authority, core activities require regular and systematic monitoring at scale, or core activities involve large-scale special category/criminal data processing.',
 'To designate DPO where mandatory.',
 'Assess DPO requirement against criteria. Designate DPO if criteria met. Document assessment even if not required. Consider voluntary DPO appointment.',
 'high', 92, true,
 'Assess DPO requirement. Verify: 1) Is requirement assessed? 2) Are all criteria considered? 3) Is DPO designated if required? 4) Is assessment documented?'),

('GDPR-37.2', 'gdpr', '37.5', 'Governance', 'DPO',
 'DPO Qualifications',
 'Designate DPO based on professional qualities, expert knowledge of data protection law and practices, and ability to fulfill tasks.',
 'To ensure DPO is qualified for the role.',
 'Define DPO qualification requirements. Assess candidate qualifications. Verify knowledge through certification or experience. Support ongoing training.',
 'high', 90, true,
 'Evaluate DPO qualifications. Check: 1) Are requirements defined? 2) Are qualifications assessed? 3) Is expertise verified? 4) Is training supported?'),

('GDPR-37.3', 'gdpr', '37.6', 'Governance', 'DPO',
 'DPO Availability',
 'Ensure DPO is available to fulfill tasks whether as staff member or external contractor.',
 'To ensure adequate DPO capacity.',
 'Allocate sufficient time for DPO tasks. Ensure accessibility. For external DPO, define availability requirements in contract.',
 'medium', 87, true,
 'Assess DPO availability. Verify: 1) Is sufficient time allocated? 2) Is DPO accessible? 3) For external DPO, is availability contractually defined?'),

-- Article 38: Position of DPO
('GDPR-38.1', 'gdpr', '38.1', 'Governance', 'DPO Independence',
 'DPO Involvement',
 'Involve DPO properly and in a timely manner in all issues relating to protection of personal data.',
 'To ensure DPO can fulfill oversight function.',
 'Include DPO in relevant decisions. Consult before processing changes. Inform of data protection issues. Document involvement.',
 'high', 91, true,
 'Evaluate DPO involvement. Check: 1) Is DPO included in decisions? 2) Is DPO consulted on changes? 3) Is DPO informed of issues? 4) Is involvement documented?'),

('GDPR-38.2', 'gdpr', '38.2', 'Governance', 'DPO Resources',
 'DPO Resources and Access',
 'Provide DPO with resources necessary to carry out tasks, access to personal data and processing operations, and to maintain expert knowledge.',
 'To enable DPO to perform duties effectively.',
 'Allocate budget and staff resources. Provide access to all processing operations. Support training and development.',
 'high', 90, true,
 'Assess DPO resources. Verify: 1) Are resources allocated? 2) Is access provided? 3) Is training supported?'),

('GDPR-38.3', 'gdpr', '38.3', 'Governance', 'DPO Independence',
 'DPO Independence',
 'Ensure DPO does not receive instructions regarding the exercise of tasks. Do not dismiss or penalize for performing tasks.',
 'To protect DPO independence.',
 'Establish DPO reporting line to highest management. Prohibit instructions on task performance. Protect against retaliation. Document independence.',
 'high', 93, true,
 'Evaluate DPO independence. Check: 1) Is reporting to highest level? 2) Are instructions prohibited? 3) Is dismissal protection in place? 4) Is independence documented?'),

('GDPR-38.4', 'gdpr', '38.5', 'Governance', 'DPO Confidentiality',
 'DPO Professional Secrecy',
 'Ensure DPO is bound by professional secrecy or confidentiality concerning the performance of tasks.',
 'To protect confidential information handled by DPO.',
 'Include confidentiality obligation in DPO contract/appointment. Extend to staff assisting DPO. Cover information received from data subjects.',
 'medium', 85, true,
 'Assess DPO confidentiality. Verify: 1) Is confidentiality obligation documented? 2) Does it cover all relevant information? 3) Does it extend to DPO staff?'),

('GDPR-38.5', 'gdpr', '38.6', 'Governance', 'DPO Role',
 'DPO Conflict of Interest Management',
 'Ensure DPO other tasks and duties do not result in conflict of interest.',
 'To prevent conflicts compromising DPO function.',
 'Define conflicting roles (e.g., head of IT, HR, marketing). Ensure DPO does not hold conflicting positions. Document conflict assessment.',
 'high', 89, true,
 'Evaluate conflict management. Check: 1) Are conflicting roles defined? 2) Is DPO free from conflicts? 3) Is assessment documented?'),

-- Article 39: Tasks of DPO
('GDPR-39.1', 'gdpr', '39.1.a', 'Governance', 'DPO Tasks',
 'DPO Information and Advice',
 'DPO informs and advises controller/processor and employees on data protection obligations.',
 'To ensure organization receives data protection guidance.',
 'Establish advisory mechanisms. Document advice provided. Track advice implementation. Review advice effectiveness.',
 'high', 91, true,
 'Assess DPO advisory function. Verify: 1) Are advisory mechanisms established? 2) Is advice documented? 3) Is implementation tracked?'),

('GDPR-39.2', 'gdpr', '39.1.b', 'Governance', 'DPO Tasks',
 'DPO Compliance Monitoring',
 'DPO monitors compliance with GDPR and other data protection provisions, and with controller/processor policies.',
 'To ensure ongoing compliance monitoring.',
 'Conduct regular compliance assessments. Monitor policy compliance. Report findings to management. Track remediation.',
 'high', 93, true,
 'Evaluate compliance monitoring. Check: 1) Are assessments conducted? 2) Is policy compliance monitored? 3) Are findings reported? 4) Is remediation tracked?'),

('GDPR-39.3', 'gdpr', '39.1.c', 'Governance', 'DPO Tasks',
 'DPO DPIA Advice',
 'DPO provides advice on data protection impact assessments and monitors performance.',
 'To ensure quality of DPIAs.',
 'Involve DPO in DPIA process. Seek DPO advice on methodology. DPO reviews and approves DPIAs. DPO monitors DPIA commitments.',
 'high', 90, true,
 'Assess DPIA advisory role. Verify: 1) Is DPO involved in DPIAs? 2) Does DPO advise on methodology? 3) Does DPO review DPIAs? 4) Does DPO monitor commitments?'),

('GDPR-39.4', 'gdpr', '39.1.d', 'Governance', 'DPO Tasks',
 'DPO Supervisory Authority Cooperation',
 'DPO cooperates with the supervisory authority.',
 'To facilitate regulatory relationship.',
 'DPO serves as point of contact for SA. Facilitates SA inquiries. Supports SA audits. Documents SA interactions.',
 'high', 89, true,
 'Evaluate SA cooperation. Check: 1) Is DPO SA contact point? 2) Are inquiries facilitated? 3) Are audits supported? 4) Are interactions documented?'),

('GDPR-39.5', 'gdpr', '39.1.e', 'Governance', 'DPO Tasks',
 'DPO Contact Point',
 'DPO acts as contact point for supervisory authority on processing issues including prior consultation.',
 'To provide consistent regulatory contact.',
 'Designate DPO as SA contact. Route SA communications through DPO. DPO manages prior consultations.',
 'medium', 86, true,
 'Assess contact point function. Verify: 1) Is DPO designated as SA contact? 2) Are communications routed through DPO? 3) Does DPO manage prior consultation?'),

('GDPR-39.6', 'gdpr', '39.2', 'Governance', 'DPO Tasks',
 'DPO Risk-Based Approach',
 'DPO has due regard to risk associated with processing operations, considering nature, scope, context, and purposes.',
 'To ensure DPO applies risk-based oversight.',
 'Apply risk-based prioritization to DPO activities. Focus oversight on higher-risk processing. Document risk considerations.',
 'medium', 84, false,
 'Evaluate risk-based approach. Check: 1) Is prioritization risk-based? 2) Is focus on higher-risk processing? 3) Are risk considerations documented?'),

-- ============================================================================
-- CHAPTER V: TRANSFERS (Articles 44-49) - 22 Controls
-- ============================================================================

-- Article 44: General Principle for Transfers
('GDPR-44.1', 'gdpr', '44.1', 'Transfers', 'General Principle',
 'Transfer Safeguard Verification',
 'Ensure any transfer of personal data to third country or international organization only takes place if conditions of Chapter V are complied with.',
 'To ensure lawful international transfers.',
 'Identify all international transfers. Verify transfer mechanism for each. Document lawfulness. Review regularly.',
 'critical', 97, true,
 'Assess transfer compliance. Verify: 1) Are transfers identified? 2) Is mechanism verified for each? 3) Is lawfulness documented? 4) Are transfers reviewed?'),

-- Article 45: Transfers Based on Adequacy Decision
('GDPR-45.1', 'gdpr', '45.1', 'Transfers', 'Adequacy',
 'Adequacy Decision Verification',
 'For transfers based on adequacy decision, verify current adequacy decision exists for destination country or organization.',
 'To ensure adequacy-based transfers are valid.',
 'Check EC adequacy decisions list. Verify decision covers destination. Monitor for adequacy decision changes. Document verification.',
 'high', 93, true,
 'Evaluate adequacy verification. Check: 1) Is adequacy decision verified? 2) Does it cover destination? 3) Are changes monitored? 4) Is verification documented?'),

-- Article 46: Transfers Subject to Appropriate Safeguards
('GDPR-46.1', 'gdpr', '46.1', 'Transfers', 'Safeguards',
 'Appropriate Safeguards Implementation',
 'In absence of adequacy decision, implement appropriate safeguards with enforceable data subject rights and effective legal remedies.',
 'To enable transfers without adequacy decision.',
 'Identify available safeguard mechanisms. Implement appropriate safeguard. Ensure enforceability. Document implementation.',
 'critical', 95, true,
 'Assess safeguard implementation. Verify: 1) Is safeguard mechanism identified? 2) Is it properly implemented? 3) Is enforceability ensured? 4) Is implementation documented?'),

('GDPR-46.2', 'gdpr', '46.2.a', 'Transfers', 'Safeguards',
 'Binding Corporate Rules',
 'Where using BCRs as transfer mechanism, ensure BCRs approved by competent supervisory authority and contain all required elements.',
 'To enable intra-group transfers under approved BCRs.',
 'Develop BCRs with required elements. Obtain SA approval. Implement BCR requirements. Monitor compliance.',
 'high', 88, false,
 'Evaluate BCR implementation. Check: 1) Are BCRs developed with required elements? 2) Is SA approval obtained? 3) Are requirements implemented? 4) Is compliance monitored?'),

('GDPR-46.3', 'gdpr', '46.2.c', 'Transfers', 'Safeguards',
 'Standard Contractual Clauses',
 'Where using SCCs as transfer mechanism, implement the SCCs adopted by the Commission or approved by supervisory authority.',
 'To enable transfers under standardized contractual protections.',
 'Use current Commission-adopted SCCs. Complete all modules correctly. Execute with recipients. Conduct transfer impact assessments. Implement supplementary measures if needed.',
 'critical', 96, true,
 'Assess SCC implementation. Verify: 1) Are current SCCs used? 2) Are modules completed correctly? 3) Are TIAs conducted? 4) Are supplementary measures implemented if needed?'),

('GDPR-46.4', 'gdpr', '46.3', 'Transfers', 'Safeguards',
 'Ad Hoc Contractual Clauses',
 'Where using ad hoc contractual clauses, obtain supervisory authority authorization before transfer.',
 'To enable transfers under custom contractual terms.',
 'Develop ad hoc clauses ensuring equivalent protection. Seek SA authorization. Document approval. Implement terms.',
 'medium', 82, false,
 'Evaluate ad hoc clauses. Check: 1) Are clauses developed? 2) Is SA authorization obtained? 3) Is approval documented? 4) Are terms implemented?'),

('GDPR-46.5', 'gdpr', '46.2.a-bis', 'Transfers', 'Safeguards',
 'Codes of Conduct for Transfers',
 'Where using approved codes of conduct for transfers, ensure binding commitments from third-country recipients.',
 'To enable transfers under approved industry codes.',
 'Verify code is approved for transfers. Obtain recipient binding commitment. Document commitments. Monitor adherence.',
 'medium', 84, false,
 'Assess code of conduct use. Verify: 1) Is code approved for transfers? 2) Are recipient commitments obtained? 3) Are commitments documented? 4) Is adherence monitored?'),

('GDPR-46.6', 'gdpr', '46.2.e', 'Transfers', 'Safeguards',
 'Certification for Transfers',
 'Where using certification mechanism for transfers, ensure valid certification with binding commitments.',
 'To enable transfers under certified protection.',
 'Verify certification is approved for transfers. Obtain recipient certification evidence. Document commitments. Monitor validity.',
 'medium', 83, false,
 'Evaluate certification use. Check: 1) Is certification valid for transfers? 2) Is evidence obtained? 3) Are commitments documented? 4) Is validity monitored?'),

-- Article 47: Binding Corporate Rules
('GDPR-47.1', 'gdpr', '47.1', 'Transfers', 'BCRs',
 'BCR Content Requirements',
 'Ensure BCRs contain all required elements: group structure, transfers covered, binding nature, principles application, rights mechanisms, acceptance of liability, and more.',
 'To ensure BCR completeness.',
 'Develop BCRs with all Article 47(2) elements. Review for completeness. Update when structure or processing changes.',
 'high', 87, false,
 'Assess BCR content. Check presence of: 1) Group structure 2) Transfers covered 3) Binding nature 4) Principles 5) Rights 6) Liability 7) Training 8) Audit'),

('GDPR-47.2', 'gdpr', '47.2', 'Transfers', 'BCRs',
 'BCR Approval Maintenance',
 'Maintain BCR approval through consistency mechanism, notify changes, and renew as required.',
 'To ensure ongoing BCR validity.',
 'Notify SA of material changes. Seek re-approval if required. Maintain approval documentation. Conduct periodic reviews.',
 'medium', 85, false,
 'Evaluate BCR maintenance. Verify: 1) Are changes notified? 2) Is re-approval sought when needed? 3) Is documentation maintained? 4) Are reviews conducted?'),

-- Article 48: Transfers Not Authorized by Union Law
('GDPR-48.1', 'gdpr', '48.1', 'Transfers', 'Third-Country Law',
 'Third-Country Legal Requests',
 'Do not recognize or enforce third-country judgments or administrative authority decisions requiring data transfer unless based on international agreement.',
 'To prevent unauthorized disclosure to third-country authorities.',
 'Develop policy on third-country legal requests. Consult legal counsel. Verify international agreement basis. Document handling.',
 'high', 91, false,
 'Assess third-country request handling. Verify: 1) Is policy established? 2) Is legal counsel involved? 3) Is international agreement basis verified? 4) Is handling documented?'),

-- Article 49: Derogations
('GDPR-49.1', 'gdpr', '49.1.a', 'Transfers', 'Derogations',
 'Explicit Consent for Transfers',
 'Where relying on explicit consent for transfers, inform data subject of risks and obtain explicit consent.',
 'To enable transfers based on informed explicit consent.',
 'Provide specific risk information for transfers. Obtain explicit (not implied) consent. Document consent with risk acknowledgment.',
 'medium', 86, true,
 'Evaluate transfer consent. Check: 1) Are specific risks disclosed? 2) Is consent explicit? 3) Is risk acknowledgment documented?'),

('GDPR-49.2', 'gdpr', '49.1.b', 'Transfers', 'Derogations',
 'Contract Performance Transfers',
 'Where transfer necessary for contract performance, ensure transfer is truly necessary (not merely convenient) for contract between data subject and controller.',
 'To correctly apply contract performance derogation.',
 'Assess necessity of transfer for contract performance. Document necessity assessment. Limit to what is truly necessary.',
 'medium', 84, false,
 'Assess contract necessity. Verify: 1) Is necessity assessed? 2) Is transfer truly necessary (not convenient)? 3) Is assessment documented?'),

('GDPR-49.3', 'gdpr', '49.1.c', 'Transfers', 'Derogations',
 'Contract in Data Subject Interest',
 'Where transfer necessary for contract in data subject''s interest, ensure contract is genuinely in their interest and transfer is necessary for its performance.',
 'To correctly apply contract-in-interest derogation.',
 'Verify contract is in data subject interest. Assess transfer necessity. Document assessment.',
 'medium', 83, false,
 'Evaluate interest contract transfers. Check: 1) Is contract in data subject interest? 2) Is transfer necessary? 3) Is assessment documented?'),

('GDPR-49.4', 'gdpr', '49.1.d', 'Transfers', 'Derogations',
 'Important Public Interest Transfers',
 'Where relying on important public interest, verify the interest is recognized in Union or Member State law.',
 'To correctly apply public interest derogation.',
 'Identify applicable public interest basis. Verify recognition in law. Document legal basis and necessity.',
 'high', 88, false,
 'Assess public interest transfers. Verify: 1) Is interest identified? 2) Is it recognized in law? 3) Is basis documented?'),

('GDPR-49.5', 'gdpr', '49.1.e', 'Transfers', 'Derogations',
 'Legal Claims Transfers',
 'Where transfer necessary for legal claims, ensure transfer is necessary for establishment, exercise, or defense of claims.',
 'To correctly apply legal claims derogation.',
 'Assess whether transfer is necessary for claims. Limit to what is necessary. Document assessment.',
 'medium', 85, false,
 'Evaluate claims transfers. Check: 1) Is transfer necessary for claims? 2) Is it limited appropriately? 3) Is assessment documented?'),

('GDPR-49.6', 'gdpr', '49.1.f', 'Transfers', 'Derogations',
 'Vital Interests Transfers',
 'Where data subject is incapable of consent and transfer necessary for vital interests, ensure genuine vital interest and data subject incapacity.',
 'To correctly apply vital interests derogation.',
 'Verify data subject incapacity. Confirm vital interests necessity. Document circumstances.',
 'high', 87, false,
 'Assess vital interests transfers. Verify: 1) Is data subject incapable? 2) Is vital interest genuine? 3) Are circumstances documented?'),

('GDPR-49.7', 'gdpr', '49.1.g', 'Transfers', 'Derogations',
 'Public Register Transfers',
 'Where transferring from public register, ensure register is intended for public consultation and conditions for consultation are met.',
 'To correctly apply public register derogation.',
 'Verify public register status. Confirm consultation conditions met. Do not transfer entire register unless permitted.',
 'low', 78, false,
 'Evaluate register transfers. Check: 1) Is it a public register? 2) Are consultation conditions met? 3) Is scope appropriate?'),

('GDPR-49.8', 'gdpr', '49.2', 'Transfers', 'Derogations',
 'Compelling Legitimate Interests Transfers',
 'Where using compelling legitimate interests derogation, ensure transfer is not repetitive, concerns limited number of data subjects, is necessary for compelling interests not overridden by data subject interests, and all circumstances assessed.',
 'To correctly apply compelling interests derogation.',
 'Verify non-repetitive nature. Confirm limited scope. Document compelling interests assessment. Notify supervisory authority. Inform data subject.',
 'medium', 82, false,
 'Assess compelling interests. Check: 1) Is transfer non-repetitive? 2) Is scope limited? 3) Are interests compelling? 4) Is SA notified? 5) Is data subject informed?'),

('GDPR-49.9', 'gdpr', '49.3', 'Transfers', 'Derogations',
 'Transfer Documentation',
 'Document transfers under derogations in records of processing activities.',
 'To maintain complete transfer records.',
 'Record derogation-based transfers in ROPA. Include derogation relied upon. Document assessment.',
 'medium', 86, true,
 'Evaluate transfer documentation. Verify: 1) Are derogation transfers in ROPA? 2) Is derogation type recorded? 3) Is assessment documented?')

ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  objective = EXCLUDED.objective,
  implementation_guidance = EXCLUDED.implementation_guidance,
  risk_category = EXCLUDED.risk_category,
  implementation_priority = EXCLUDED.implementation_priority,
  automated_test_available = EXCLUDED.automated_test_available,
  ai_assessment_prompt = EXCLUDED.ai_assessment_prompt;

-- Update framework control count
UPDATE compliance_frameworks
SET metadata = jsonb_set(
  COALESCE(metadata, '{}'),
  '{control_count}',
  (SELECT COUNT(*)::text::jsonb FROM compliance_controls WHERE framework_id = 'gdpr')
)
WHERE id = 'gdpr';

-- Log migration completion
DO $$
BEGIN
  RAISE NOTICE 'GDPR controls migration complete. Total controls: %',
    (SELECT COUNT(*) FROM compliance_controls WHERE framework_id = 'gdpr');
END $$;
